Backend frontend connection
SOEN-341-Project/Group-P-soen341project2022 pull request #97
Opened 2022-03-18 19:48 UTC by Adamo-O

## Brief Description
Linked backend Google Cloud with frontend React app.

## Linked Issues
- closes #96 

## Changes
### Frontend
- Used Axios for HTTP Requests (GET, POST, DELETE)
- Converted use of test data to appropriate API request
- Features using Google Cloud backend:
   - View products in grid
   - View product details in page
   - Sellers can view products
   - Sellers can modify existing products
   - Sellers can add products
   - Sellers can delete products

### Backend
- Added a route that lists all sellers
- Brand descriptions are not required in requests
- Brand names must be unique
- Brands deleted if they have no attached products

## Additional context
For a guide on all requests and routes to the backend, visit the [How to use the backend guide](https://github.com/SOEN-341-Project/Group-P-soen341project2022/wiki/How-to-use-the-backend).

2022-03-19 19:18 UTC, aspyridakos submitted a review, later dismissed
Nice! ⚡ 💯 ⚡

2022-03-19 20:02 UTC, emma-amar approved these changes
looks great!! thanks for setting it all up !!! :-))

2022-03-20 18:56 UTC, oumbarry approved these changes
Great work

2022-03-20 18:56 UTC, jungsoolee1 submitted a review, later dismissed
Nicely explained. Thank you so much!

2022-03-20 19:45 UTC, aspyridakos approved these changes

2022-03-20 19:45 UTC, jungsoolee1 approved these changes
Good job

2022-03-20 19:48 UTC, aspyridakos requested changes

2022-03-20 19:48 UTC, aspyridakos commented on online-shopping-website/frontend/src/Components/Products/SideNav.js
> -    function iterateSellers() {
Should be called iterateBrands

2022-03-20 19:48 UTC, aspyridakos commented on online-shopping-website/frontend/src/Components/Products/SideNav.js
> +    function iterateSellers(props) {
same as above

2022-03-20 19:54 UTC, oumbarry approved these changes
Good pr!

2022-03-20 19:56 UTC, aspyridakos submitted a review, later dismissed

2022-03-20 20:00 UTC, KooshaG commented on online-shopping-website/frontend/src/Components/Products/SideNav.js
> +    function iterateSellers(props) {
It's changed!

2022-03-20 20:01 UTC, KooshaG commented on online-shopping-website/frontend/src/Components/Products/SideNav.js
> -    function iterateSellers() {
It's changed!

2022-03-20 20:21 UTC, aspyridakos approved these changes
Looking good:)

2022-03-20 20:24 UTC, merged